### PR TITLE
Add Czech locale (cs_CZ)

### PR DESCRIPTION
**Pull request by bartholomej**
Added Czech locale ;)

### CODE REVIEW

**Comment by bartholomej** [comment]
Hi @boo1ean Anything I can do for this PR to be merged in?

**Comment by bartholomej** [comment]
@boo1ean Anything I can fix or change on this PR? ;) Thx

**Comment by expelledboy** [comment]
http://cdn.frustra.org/sounds/sound_portal1/npc/turret_floor/turret_autosearch_5.mp3?id=308

**Comment by boo1ean** [comment]
My apologies :) I need some more hands to work on this project

**Comment by expelledboy** [comment]
@boo1ean I would be happy to assist?

**Pull request merged**
