### PR TITLE
Added misc/boolean, returns true or false

### PR DESCRIPTION
**Pull request by chamini2**

### CODE REVIEW

**Comment by boo1ean** [comment]
Hi, thanks for contribution.
You should use internal `RNG` function not `Math.random`, see other generators.
Pls update your PR, and I'll merge and release it.

**Comment by chamini2** [comment]
Hey @boo1ean, I just realized of the `coin_flip` under `numbers`, should I just do an alias to it or `return this.random < 0.5` ?

**Comment by boo1ean** [comment]
I forgot about `coin_flip`, I guess you could make an alias, `boolean` is more logical name for some cases

**Comment by chamini2** [comment]
@boo1ean, ready to merge then.

**Comment by boo1ean** [comment]
Thank you!

**Pull request merged**
