### PR TITLE
Typings extended

### PR DESCRIPTION
**Pull request by robertohuertasm**
I've added helpers and generator functions.

### CODE REVIEW

**Comment by robertohuertasm** [comment]
Hi, this is also a little bit of a critic update as the old export structure used was not correct and will not work with TypeScript. I've fixed it here now. 

People should import your library like this:
`import * as casual from 'casual'`

Many thanks for your amazing library!! :wink:

**Comment by Klowner** [comment]
Is this a fix for #48 ?

**Comment by robertohuertasm** [comment]
Yes it is.

**Comment by robertohuertasm** [comment]
@Klowner do you have an idea about when this could be merged? It's making it difficult to work with your library without this. :disappointed:

**Comment by boo1ean** [comment]
Hi, I'm going to do it right now. Thanks for contribution!

**Comment by boo1ean** [comment]
Published!
`+ casual@1.5.5`

**Comment by robertohuertasm** [comment]
Thanks!!! :+1:

**Comment by Klowner** [comment]
`casual-browserify@1.5.5` is published as well, not sure which one you're using :)

**Comment by robertohuertasm** [comment]
@Klowner I'm using @boo1ean's version right now. Anyway, it's good news! Thanks! :grinning:

**Pull request merged**
