### PR TITLE
Add locale nb_NO

### PR DESCRIPTION
**Pull request by sskogen**

### CODE REVIEW

**Comment by sskogen** [comment]
@ljharb: If I'm right (not very experienced with Travis and npm versioning), this build fails of the same reason as your first commit in #51. You fixed the build by adding a before_install script in the second commit, but it doesn't seem to work in my case.

**Comment by ljharb** [comment]
The issue is that this project updated to yarn, which doesn't work on node 0.8.

@boo1ean if you use yarn, you've dropped support for node 0.8 in your tests - that means that for this project, adding yarn is a semver-major bump, and 0.8 should be thus removed from travis.yml.

Alternatively, you could stick with normal npm, since yarn doesn't encompass the same functionality.

**Comment by sskogen** [comment]
Thanks for the quick answer @ljharb :) What do you want me to do here @boo1ean?

**Comment by ljharb** [comment]
Turns out `yarn.lock` was commited by accident in #56. I've opened #64 to correct this - once that's merged, and this PR is rebased, tests will pass in node 0.8.

**Comment by boo1ean** [comment]
Sorry for delay, merged both PR's and published `casual@1.5.12`

**Pull request merged**
